### PR TITLE
Remove Privacy Labels and Declarations

### LINKED ISSUE #45: Privacy Labels/Declaration should be removed
[[
Such a document is not currently being incubated at W3C, as far as I can tell. Not only is it not currently being incubated, it’s never even been proposed for incubation! I wasn’t able to find anything resembling it in either WICG’s or Privacy CG’s proposals repos:

* https://github.com/privacycg/proposals/issues
* https://github.com/WICG/proposals/issues

It got added to the charter in [3a94387](https://github.com/w3cping/administrivia/commit/3a9438795afceb656e2395d1aa8ea9fc2e3eb3fc), but that commit doesn’t cite an issue or pull request so I’ve been unable to track down a justification or rationale for including such a deliverable before it’s even been proposed for incubation, much less incubated,

It’s hard to know if if such a document is worth producing with so little to go on. But, if it is, I’d rather its proponents do the work of incubating it in a Community Group. If it’s got legs, they can propose to add it to the list of WG deliverables in its next round of chartering.
]]
From [AC Review 2023](https://www.w3.org/2002/09/wbs/33280/privacy-wg-2023/results)

### PR DESCRIPTION
**Pull request by plehegar**
Fixes #45

### CODE REVIEW

**Review by npdoty — APPROVED** [review]
Looks fine to me.

**Comment by npdoty** [comment]
Some context on this charter item:

I proposed this potential future deliverable based on discussions at W3C meetings and workshops, as a response to the idea of narrowing the charter's scope to only specified deliverables but providing the group with the option to take on work in the future without relying on another re-charter and Advisory Committee review process. In PING discussions, there was some support for that general idea (of more flexible scope / not needing recharters), but no particular commitment to this particular deliverable. Given that, I suspect that the participants will not object to or be blocked by removing this deliverable, and I'm fine with removing it.

In the future, I think we need more effective mechanisms for either: faster re-charter processes with quick but engaged AC review; or, broader scope charters where WGs can decide whether to pick up in-scope items that are ready. For W3C generally, as has been repeatedly noted in AC meetings, very narrow group charters that get updated and reviewed very slowly with little AC participation is not an effective recipe for conducting effective W3C work.

**Review by pes10k — APPROVED** [review]
lgtm

**Review by hober — APPROVED** [review]
Looks good to me!

**Comment by hober** [comment]
> Looks good to me!

Oh, and I should say that, if applied, this PR addresses the concern voiced in our FO.

**Review by tantek — APPROVED** [review]
Thank you for this edit. This would resolve a potential FO from Mozilla.

**Comment by mnot** [comment]
I'm glad to see that this appears to be able to be resolved amicably, but that may not always be the case, and there is no Process basis AFAIK for incubation to take place in a certain way. If we have a requirement for incubation, it should be made explicit in the Process.

**Comment by npdoty** [comment]
I don't know if it has to be an update to the Process document specifically, but we do urgently need better documentation of current best/preferred practices for incubation, if we want charters to work in a consistent way and if the AC wants to better anticipate and improve their charter reviews. I believe Tantek has indicated that the AB will contribute to this.

**Pull request merged**
